# Just for testing training pipeline on CPU with minimal epochs and data
_target_: lightning.pytorch.trainer.Trainer
default_root_dir: ${exp_dir}
max_epochs: 2
accelerator: cpu  
devices: 1
precision: 32  
gradient_clip_val: 1.0
fast_dev_run: false        
num_sanity_val_steps: 0      # Skip sanity check completely
limit_train_batches: 2     
limit_val_batches: 1       
limit_test_batches: 1        
log_every_n_steps: 1  