_target_: lightning.pytorch.trainer.Trainer
default_root_dir: ${hydra:runtime.output_dir}
max_epochs: 75
accelerator: gpu
strategy: ddp
devices: auto
precision: 16-mixed
gradient_clip_val: 1.0
logger: ${logger}
callbacks: ${callbacks}
fast_dev_run: False