name: unet_convlstm
instance:
  _target_: src.models.fcn_crnn.FCN_CRNN
  num_classes: ${dataset.num_classes}
  in_channels: ${dataset.num_channels}
  img_res: ${dataset.img_size} 
  train_stage: 2                                        
  attn_channels: 128             
  cscl_win_size: 3         
  cscl_win_dilation: 1     
  cscl_win_stride: 1            
  attn_groups: 1                      
  crnn_model_name: "clstm"         
  bidirectional: false                
  avg_hidden_states: true             
  pretrained: false                   
  early_feats: false                
  br_layer: false                     