_target_: lightning.pytorch.loggers.wandb.WandbLogger              
project: Sen12Landslides
name: ${model.name}_${dataset.name}_${exp_tag}_${now:%Y-%m-%d_%H-%M-%S}
save_dir: ${hydra:runtime.output_dir}
id: null
resume: False
offline: False                 
anonymous: null                    
log_model: False                   
prefix: null                        
group: null
tags:
  - ${model.name}
  - ${dataset.name}
  - seed=${seed}