# configs/dataset/sen12ls_s2.yaml
name: sen12ls_s2 
root: ${root_dir} # or /path/to/Sen12Landslides where data is located
task: S12LS-LD
modality: s2
timeseries_len: 15
img_size: 128
num_classes: 1
num_channels: 11 # or 11 if dem=true
dem: true
min_date: "2015-12-03"
nodata_value: -9999.0