# configs/dataset/sen12ls_s1dsc.yaml
name: sen12ls_s1dsc
root: ${root_dir}/data_harmonized # or /data_raw
task: S12LS-LD
modality: s1dsc
timeseries_len: 15
img_size: 128
num_classes: 1
num_channels: 2 # or 3 if dem=true
dem: false
min_date: "2015-12-03"
nodata_value: -9999.0