# configs/dataset/sen12ls_s2.yaml
name: sen12ls_s2
root: /dss/dsstbyfs02/pn49cu/pn49cu-dss-0006/Sen12Landslides
task: S12LS-LD-new
modality: s2
timeseries_len: 15
img_size: 128
num_classes: 1
num_channels: 11 # or 11 if dem=true
dem: true
min_date: "2015-12-03"
nodata_value: -9999.0