- _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${hydra:runtime.output_dir}/checkpoints
  filename: "best.ckpt"
  monitor: "val/IoU"
  save_top_k: 1
  mode: "max"
  save_last: true

- _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: "val/IoU"
  patience: 20
  min_delta: 1e-4
  mode: "max"
  verbose: true