# configs/datamodule/sen12ls.yaml
_target_: src.data.datamodule.Sen12LsDataModule
dataset_cfg: ${dataset}
batch_size: 16
num_workers: 16
train_transforms:
  _target_: torchvision.transforms.Compose 
  transforms:
    - _target_: src.data.transforms.RandomHorizontalFlip
      p: 0.5
    - _target_: src.data.transforms.RandomVerticalFlip
      p: 0.5
    - _target_: src.data.transforms.RandomRotate90
      p: 0.5
    - _target_: src.data.transforms.Normalize
      # norm_json: ${root_dir}/tasks/${dataset.task}/${dataset.modality}/norm.json
      norm_json: /dss/dsstbyfs02/pn49cu/pn49cu-dss-0006/Sen12Landslides/tasks/S12LS-LD-HQ/s2/norm.json
val_transforms: 
  _target_: torchvision.transforms.Compose 
  transforms:
    - _target_: src.data.transforms.Normalize
      # norm_json: ${root_dir}/tasks/${dataset.task}/${dataset.modality}/norm.json
      norm_json: /dss/dsstbyfs02/pn49cu/pn49cu-dss-0006/Sen12Landslides/tasks/S12LS-LD-HQ/s2/norm.json
test_transforms:
  _target_: torchvision.transforms.Compose 
  transforms:
    - _target_: src.data.transforms.Normalize
      # norm_json: ${root_dir}/tasks/${dataset.task}/${dataset.modality}/norm.json
      norm_json: /dss/dsstbyfs02/pn49cu/pn49cu-dss-0006/Sen12Landslides/tasks/S12LS-LD-HQ/s2/norm.json
pin_memory: true